name: fuga_loop
length: 170
track_padding: 0
round_up_time: 0
tracks:
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
  - fuga
