- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 10
  minute: 45
  second: 0
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 11
  minute: 5
  second: 43
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 11
  minute: 26
  second: 26
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 11
  minute: 47
  second: 9
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 12
  minute: 7
  second: 52
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 12
  minute: 28
  second: 35
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 12
  minute: 49
  second: 18
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 13
  minute: 10
  second: 1
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 13
  minute: 30
  second: 44
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 13
  minute: 51
  second: 27
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 14
  minute: 12
  second: 10
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 14
  minute: 32
  second: 53
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 14
  minute: 53
  second: 36
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 15
  minute: 14
  second: 19
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 15
  minute: 35
  second: 2
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 15
  minute: 55
  second: 45
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 16
  minute: 16
  second: 28
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 16
  minute: 37
  second: 11
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 16
  minute: 57
  second: 54
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 17
  minute: 18
  second: 37
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 17
  minute: 39
  second: 20
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 18
  minute: 0
  second: 3
- track_id: fuga
  audio_index: 20 # included for compatibility 
  video_index: 19  # included for compatibility 
  command: play
  day_of_week: 0,1,2,3,4,5,6
  hour: 18
  minute: 20
  second: 46
